; Local override of Neovim's runtime markdown highlights query.
;
; WHY THIS FILE EXISTS
; --------------------
; Neovim 0.12.1 / 0.12.2 has a bug where the directive
;   (#set! conceal_lines "")
; on `fenced_code_block_delimiter` and `info_string > language` nodes
; can trigger an internal error during treesitter injection processing:
;
;   .../vim/treesitter/languagetree.lua:215:
;   .../vim/treesitter/treesitter.lua:196:
;   attempt to call method 'range' (a nil value)
;
; Upstream issue (closed as "Not planned"):
;   https://github.com/neovim/neovim/issues/39032
;
; SEE ALSO: SIBLING OVERRIDE injections.scm
; -----------------------------------------
; In this configuration the same `attempt to call method 'range'` error
; ALSO fires from a separate trigger inside the markdown injections
; query shipped by nvim-treesitter (master branch). Removing
; `conceal_lines` from highlights alone is NOT sufficient -- you still
; need `queries/markdown/injections.scm` next to this file. See that
; file's header comment for the second trigger and its fix.
;
; HOW THIS OVERRIDE WORKS
; -----------------------
; This file lives in the config dir, which is prepended to 'runtimepath'
; before $VIMRUNTIME. Neovim's query loader treats the FIRST file (in rtp
; order) without a ";; extends" modeline as the base query and ignores
; later base files. See: $VIMRUNTIME/lua/vim/treesitter/query.lua
; (function `M.get_files`). Therefore this file silently replaces
; $VIMRUNTIME/queries/markdown/highlights.scm.
;
; WHAT WAS CHANGED VS UPSTREAM
; ----------------------------
; Removed the two `(#set! conceal_lines "")` directives only. The
; `(#set! conceal "")` directives are kept, so per-character concealment
; of code-fence delimiters still works; only the buggy whole-line
; concealment is dropped.
;
; MAINTENANCE
; -----------
; When upgrading Neovim, check whether the upstream query has changed
; and whether the `conceal_lines` bug is fixed.
;
; 1) Diff against the upstream query shipped with the running Neovim:
;
;      diff -u \
;        "$(nvim --headless --clean +'echo $VIMRUNTIME' +q 2>&1)"/queries/markdown/highlights.scm \
;        ~/.config/nvim-kickstart/queries/markdown/highlights.scm
;
;    The only differences should be this comment block and the two
;    deleted `(#set! conceal_lines "")` lines. If anything else differs,
;    upstream changed -- port the new captures into this file.
;
; 2) Test whether the upstream bug is fixed:
;
;      mv ~/.config/nvim-kickstart/queries/markdown/highlights.scm \
;         ~/.config/nvim-kickstart/queries/markdown/highlights.scm.bak
;      nvim some-file.md
;
;    If no `attempt to call method 'range' (a nil value)` error appears,
;    delete the .bak file (and this whole `queries/markdown/` dir).
;    Otherwise restore it:
;
;      mv ~/.config/nvim-kickstart/queries/markdown/highlights.scm.bak \
;         ~/.config/nvim-kickstart/queries/markdown/highlights.scm
;
; 3) Track the upstream issue: https://github.com/neovim/neovim/issues/39032

;From MDeiml/tree-sitter-markdown & Helix
(setext_heading
  (paragraph) @markup.heading.1
  (setext_h1_underline) @markup.heading.1)

(setext_heading
  (paragraph) @markup.heading.2
  (setext_h2_underline) @markup.heading.2)

(atx_heading
  (atx_h1_marker)) @markup.heading.1

(atx_heading
  (atx_h2_marker)) @markup.heading.2

(atx_heading
  (atx_h3_marker)) @markup.heading.3

(atx_heading
  (atx_h4_marker)) @markup.heading.4

(atx_heading
  (atx_h5_marker)) @markup.heading.5

(atx_heading
  (atx_h6_marker)) @markup.heading.6

(info_string) @label

(pipe_table_header
  (pipe_table_cell) @markup.heading)

(pipe_table_header
  "|" @punctuation.special)

(pipe_table_row
  "|" @punctuation.special)

(pipe_table_delimiter_row
  "|" @punctuation.special)

(pipe_table_delimiter_cell) @punctuation.special

; Code blocks (conceal backticks and language annotation)
(indented_code_block) @markup.raw.block

((fenced_code_block) @markup.raw.block
  (#set! priority 90))

(fenced_code_block
  (fenced_code_block_delimiter) @markup.raw.block
  (#set! conceal ""))

(fenced_code_block
  (info_string
    (language) @label
    (#set! conceal "")))

(link_destination) @markup.link.url

[
  (link_title)
  (link_label)
] @markup.link.label

((link_label)
  .
  ":" @punctuation.delimiter)

[
  (list_marker_plus)
  (list_marker_minus)
  (list_marker_star)
  (list_marker_dot)
  (list_marker_parenthesis)
] @markup.list

; NOTE: The following has been commented out due to issues with spaces in the
; list marker nodes generated by the parser. If those spaces ever get captured
; by a different node (e.g. block_continuation) we can safely re-add these
; conceals.
; ;; Conceal bullet points
; ([(list_marker_plus) (list_marker_star)]
;   @punctuation.special
;   (#offset! @punctuation.special 0 0 0 -1)
;   (#set! conceal "•"))
; ([(list_marker_plus) (list_marker_star)]
;   @punctuation.special
;   (#any-of? @punctuation.special "+" "*")
;   (#set! conceal "•"))
; ((list_marker_minus)
;   @punctuation.special
;   (#offset! @punctuation.special 0 0 0 -1)
;   (#set! conceal "—"))
; ((list_marker_minus)
;   @punctuation.special
;   (#eq? @punctuation.special "-")
;   (#set! conceal "—"))
(thematic_break) @punctuation.special

(task_list_marker_unchecked) @markup.list.unchecked

(task_list_marker_checked) @markup.list.checked

((block_quote) @markup.quote
  (#set! priority 90))

([
  (plus_metadata)
  (minus_metadata)
] @keyword.directive
  (#set! priority 90))

[
  (block_continuation)
  (block_quote_marker)
] @punctuation.special

(backslash_escape) @string.escape

(inline) @spell
